---
mysetting:
  notices: &1
    label: 通知公告
    title: 标题
    content: 内容
  reports: &2
    title: 标题
    content: 正文
  models: &3
    label: ''
    name: 名称
    image: 图像
    index: 列表
    new: 新建
    edit: 编辑
    show: 详情
    form: 表单
    js: js
    scss: scss
    admin: 添加到后台
  properties: &4
    label: 嵌套显示的属性
    name: 属性名
    tag: 标签
  relates: &5
    label: ''
    type: 关联类型
    obj: 对象
  templates: &6
    label: 模板
    name: 英文名称
    cn_name: 中文名称
    nest: 需要在页面嵌套的一对多属性
    image: 多个图片
    attachment: 多个附件
    one_image: 一个图片
    one_attachment: 一个附件
    index: 列表
    new: 新建
    edit: 编辑
    show: 详情
    form: 表单
    js: js
    scss: scss
    download: 下载表格
    upload: 上传解析表格
    admin: 添加到后台
    current_user: current_user
  natures: &7
    label: ''
    name: 英文属性名
    type: 类型
    title: 中文属性名
    tag: 标签
  spiders: &8
    label: 爬虫
    link: 请求地址
    cookie: cookie
    agent: agent
    content_type: content_type
    page: 页码
    file: 文件名带后缀
    referer: referer
    host: host
    redirection: redirection
  selectors: &9
    label: 选择器
    name: 选择器名称
    category: 类型
    title: 标题
    categories:
      text:
        info: 文本
        value: '0'
      attr:
        info: 属性
        value: '1'
      img:
        info: 图片
        value: '2'
defaults:
  admins: &10
    class_name: all
    email: myzn@world.com
    phone: '15763703188'
    password: dagening@521
  users: &11
    class_name: User
    opening: 0
    pending: 1
    rejected: 2
    passed: 3
    opening_title: 新用户
    pending_title: 待审核
    rejected_title: 不通过
    passed_title: 通过
    phone: 电话
    password: 密码
    password_confirmation: 确认密码
    name: 姓名
    identity: 身份证
    alipay: 支付宝
    status: 认证状态
    level: 等级
    inviter: 邀请者
  roles: &12
    label: 角色
    name: 名称
    class_name: Role
    super_admin: 超级管理员
    role_fct: 厂区用户
    role_wx: 微信用户
    role_grp: 集团用户
    role_cpy: 分公司用户
    role_device: 厂区-施工站点
    role_inspector: 厂区-签到负责人
    role_worker: 厂区-工人管理
    role_sign_log: 厂区-签到记录
    role_wx_device: 微信-施工站点
    role_wx_inspector: 微信-签到负责人
    role_wx_worker: 微信-工人管理
    role_wx_sign_log: 微信-签到记录
    role_grp_device: 集团-施工站点
    role_grp_inspector: 集团-签到负责人
    role_grp_worker: 集团-工人管理
    role_grp_sign_log: 集团-签到记录
  permissions: &13
    super_admin: 管理系统所有资源
    label: 权限管理
    name: 名称
    subject_class: controller单数名称
    action: action
    description: 描述
  systems: &40
    poundage: 0.1
    commision: 0.1
    authc_pay: 1
    host: http://192.168.31.20:3000
    status_en_yes: true
    status_en_no: false
    status_yes: 是
    status_no: 否
    status_public: '1'
    status_private: '0'
    default_str: ''
    default_num: 0
    default_boolean: true
    per_page: 20
    index: index
    new: new
    show: show
    delete: delete
    edit: edit
    btn_upload: 上传
    btn_back: 返回
    btn_next: 下一步
    btn_edit: 编辑
    btn_new: 添加
    btn_show: 详情
    btn_delete: 删除
    btn_save: 保存
    company_name: 山东公用水务集团农污工程签到系统
    opening: 新用户
    pending: 待审核
    rejected: 不通过
    passed: 通过
    gdkey: adb51a0594db1cd83d9e209f5cb095dd
    gdname: nwprojects
    face_group: project_wokers
    man_no: '0'
    man: 男
    woman_no: '1'
    woman: 女
  states: &14
    opening: opening
    selecting: selecting
    selected: selected
    completed: completed
    canceled: canceled
    uploading: uploading
    uploaded: uploaded
    ongoing: ongoing
    outbound: outbound
    awaiting: awaiting
    pending: pending
    passed: passed
    assign: assign
    transfer: transfer
    unsettled: unsettled
    working: working
    processing: processing
    processed: processed
    deleting: deleting
    error: error
    unaccept: unaccept
    accept: accept
  trade_orders: &15
    number: 订单编号
    price: 价格
    state: 状态
    name: 姓名
    phone: 电话
    address: 地址
    wayno: 物流信息
    opening: opening
    opening_title: 新建
    pending: pending
    pending_title: 待支付
    paid: paid
    paid_title: 已支付,待发货
    departed: departed
    departed_title: 已发货
    completed: completed
    completed_title: 已完成
    canceled: canceled
    canceled_title: 已取消
  extract_cashes: &16
    coin: 提取金额
    status: 状态
    pending: pending
    pending_title: 待审核
    agree: agree
    agree_title: 同意
    disagree: disagree
    disagree_title: 不同意
  file_libs: &17
    label: 文件库
    name: 文件名
    path: 路径
    file_type: 文件类型
    doc: '0'
    xls: '1'
    pdf: '2'
    img: '3'
    ppt: '4'
    mp4: '5'
    txt: '6'
  archives: &18
    label: 档案库
    name: 名称
    desc: 备注
  portfolios: &19
    label: 文件夹
    name: 文件夹名
  examines: &20
    label: 考核资料自选库
    name: 名称
  exm_items: &21
    label: 一级目录
    name: 一级目录名
    hierarchy: 目录树
  agendas: &22
    label: 日程
    title: 标题
    content: 事务内容
    worktime: 时间
  statistics: &23
    label: 统计
    title: 标题
    xtitle: x轴标题
    ytitle: y轴标题
    legend: 图例
    data: 数据
  companies: &24
    label: 公司
    area: 地区
    name: 名称
    info: 简介
    lnt: 经度
    lat: 维度
  factories: &25
    label: 工厂
    area: 地区
    name: 名称
    info: 简介
    design: 设计处理水量
    lnt: 经度
    lat: 维度
    plan: 计划
  departments: &26
    label: 部门
    name: 名称
    info: 简介
  charts: &27
    line: '0'
    bar: '1'
    gauge: '2'
    table: '3'
    radar: '4'
    scatter_3d: '5'
    line_t: line
    bar_t: bar
    gauge_t: gauge
    table_t: table
    radar_t: radar
    scatter_3d_t: scatter_3d
  months: &28
    one: '1'
    one_t: 一月
    two: '2'
    two_t: 二月
    three: '3'
    three_t: 三月
    four: '4'
    four_t: 四月
    five: '5'
    five_t: 五月
    six: '6'
    six_t: 六月
    seven: '7'
    seven_t: 七月
    eight: '8'
    eight_t: 八月
    nine: '9'
    nine_t: 九月
    ten: '10'
    ten_t: 十月
    eleven: '11'
    eleven_t: 十一月
    twelve: '12'
    twelve_t: 十二月
  accounts: &29
    coin: 金额
    password: 安全密码
    number: 卡号
    award_sign_up: 10
    award_check_in: 5
    award_share: 30
    award_invite_sign_up: 10
    award_invite_recharge: 40
    enable: enable
    disable: disable
  devices: &30
    label: 施工站点
    idno: 站点编号
    name: 站点名称
    mdno: 县区
    unit: 街道
    out_date: 出厂日期
    mount_date: 安装日期
    supplier: 村/社区
    mfcture: 制造商
    pos: 经度
    pos_no: 纬度
    life: 使用年限
    qrcode: 二维码
    state: 状态
    desc: 备注
    state_normal: 施工中
    state_repair: 已完工
    state_stop: 停工
  upholds: &31
    label: 巡检记录
    uphold_date: 日期
    reason: 巡检原因
    content: 巡检内容
    cost: 费用
    state: 状态
  patrolers: &32
    label: 签到负责人
    name: 姓名
    phone: 电话
    password: 密码
  tasks: &33
    label: 巡检任务
    task_date: 巡检日期
    des: 备注
  task_reports: &34
    label: 巡检报告
    longitude: 经度
    latitude: 维度
    state: 运行状态
    question: 问题
  task_logs: &41
    label: 巡检日志
    start_time: 开始时间
    end_time: 结束时间
    state: 状态
  gdservices: &35
    label: 北斗定位终端
    key: key
    name: name
    sid: sid
  gdteminals: &36
    label: 北斗地图终端
    name: name
    tid: tid
    desc: desc
  gdtraces: &37
    label: 北斗地图轨迹管理
    trid: trid
    trname: trname
  workers: &38
    label: 工人管理
    name: 姓名
    idno: 身份证
    phone: 电话
    gender: 性别
    state: 状态
    adress: 家庭住址
    idfront: 身份证正面
    idback: 身份证反面
    avatar: 一寸照片
    info: 备注
    worker: '0'
    worker_title: 工人
    supervisor: '1'
    supervisor_title: 监理
    manager: '2'
    manager_title: 总包
  sign_logs: &39
    label: 签到记录
    sign_date: 签到日期
    wx_user_id: 签到负责人
    device_id: 站点
    longitude: 经度
    latitude: 纬度
development:
  notices: *1
  reports: *2
  models: *3
  properties: *4
  relates: *5
  templates: *6
  natures: *7
  spiders: *8
  selectors: *9
  admins: *10
  users: *11
  roles: *12
  permissions: *13
  states: *14
  trade_orders: *15
  extract_cashes: *16
  file_libs: *17
  archives: *18
  portfolios: *19
  examines: *20
  exm_items: *21
  agendas: *22
  statistics: *23
  companies: *24
  factories: *25
  departments: *26
  charts: *27
  months: *28
  accounts: *29
  devices: *30
  upholds: *31
  patrolers: *32
  tasks: *33
  task_reports: *34
  task_logs:
    label: 工单日志
    wx_user_id: 办理人员
    state: 进度
  gdservices: *35
  gdteminals: *36
  gdtraces: *37
  workers: *38
  sign_logs: *39
  systems: *40
  deploys:
    label: 系统配置
    name: 名称
    start_time: 开始时间
    end_time: 结束时间
    expire: 超时
    appid: appid
    secret: secret
    key: key
    val1: val1
    val2: val2
    val3: val3
  work_orders:
    label: 工单
    title: 标题
    pdt_time: 时间
    content: 内容
    address: 地址
    urgent: 加急
    state: 状态
    order_time: 预约时间
    limit_time: 最后期限
    person: 联系人
    phone: 联系电话
    img: 图片
    number: 工单编号
  order_logs:
    label: 工单记录
    feedback: 反馈
    content: 处理结果
    longitude: 经度
    latitude: 纬度
    upman: 上一个人
    nextman: 下一个人
    start_time: 开始处理时间
    end_time: 处理完成时间
    state: 进度
    img: 照片
    address: 地址
    item: 备用
  state_tags:
    opening: 待分配
    completed: 已完成
    canceled: 已取消
    awaiting: 待确认
    assign: 已分配
    transfer: 已转单
    unsettled: 未解决
    processing: 处理中
    processed: 已处理
    unaccept: 待接单
    accept: 已接单
test: 
production:
  notices: *1
  reports: *2
  models: *3
  properties: *4
  relates: *5
  templates: *6
  natures: *7
  spiders: *8
  selectors: *9
  admins: *10
  users: *11
  roles: *12
  permissions: *13
  systems: *40
  states: *14
  trade_orders: *15
  extract_cashes: *16
  file_libs: *17
  archives: *18
  portfolios: *19
  examines: *20
  exm_items: *21
  agendas: *22
  statistics: *23
  companies: *24
  factories: *25
  departments: *26
  charts: *27
  months: *28
  accounts: *29
  devices: *30
  upholds: *31
  patrolers: *32
  tasks: *33
  task_reports: *34
  task_logs: *41
  gdservices: *35
  gdteminals: *36
  gdtraces: *37
  workers: *38
  sign_logs: *39
